name: Create GitHub Release on version change

on:
  push:
    branches:
      - master
      
permissions:
  contents: write
  
jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Get current version
      - name: Get current version
        id: get_version
        run: |
          version=$(jq -r .version package.json)
          echo "version=$version" >> $GITHUB_OUTPUT

      # Get the previous version from Git history
      - name: Get previous version
        id: get_previous_version
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            prev_version=$(git show HEAD^:package.json | jq -r .version)
          else
            prev_version=""
          fi
          echo "prev_version=$prev_version" >> $GITHUB_OUTPUT

      # Compare versions and create a release if the version has changed
      - name: Create GitHub Release if version changed
        if: steps.get_version.outputs.version != steps.get_previous_version.outputs.prev_version
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          body: |
            Автоматический релиз версии v${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
